version: "3.9"

services:
  dist-22-23s-db:
    container_name: dist-22-23s-db
    image: "postgres:15.2-bullseye"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=truve
      - POSTGRES_PASSWORD=981982
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      # external:internal
      - "5445:5432"
    volumes:
      - dist-22-23s-db-postgres-volume:/var/lib/postgresql/data

volumes:
  dist-22-23s-db-postgres-volume:

